#!/usr/bin/env bash
# Installing Nginx web server

# Updating server
sudo apt-get -y update
# Upgrading server
sudo apt-get -y upgrade
# Installing nginx
sudo apt-get -y install nginx
# Starting nginx
sudo service nginx start
# Giving permissions to file
sudo chmod 777 /var/www/html/index.nginx-debian.html
# Writing the string on the index.nginx-debian.html
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
# Asking if the program has to restart nginx
sudo sed -i '/server_name _;/ a \\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-enabled/default
# Restarting service
sudo service nginx restart
