#!/usr/bin/env bash
# Installing Nginx web server

# Updating server
sudo apt-get -y update
# Upgrading server
sudo apt-get -y upgrade
# Installing nginx
sudo apt-get -y install nginx
# Starting nginx
sudo service nginx start
# Giving permissions to file
sudo chmod 777 /var/www/html/index.nginx-debian.html
# Writing the string on the index.nginx-debian.html
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
# Redirecting web page
sudo sed -i '/server_name _;/ a \\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-enabled/default
# Restarting service
sudo service nginx restart
# Creating file custom_404.html with string
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
# Appending information in default file
sudo sed -i "20i \\\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t root /usr/share/nginx/html;\n\tinternal;\n\t}" /etc/nginx/sites-enabled/default
