#!/usr/bin/env bash

# Path parameters
export token="natalias-dashboard-tue-sep-28-71621-pm?from_ts=1632922924877&to_ts=1632926524877&live=true"
# Curl command
# Curl command
curl -X GET "https://api.datadoghq.com/api/v1/dashboard/public/${token}" \
-H "Content-Type: application/json" \
-H "DD-API-KEY: ${DD_API_KEY}" \
-H "DD-APPLICATION-KEY: ${DD_APP_KEY}"