#!/usr/bin/env bash
# Changing way
ls -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sed -i "/listen [::]:80 default_server ipv6only=on;/ listen [::]:80 default_server;/" /etc/nginx/sites-available/default
sudo service nginx restart
