#!/usr/bin/env bash
# Writing a Bash script that displays:
# - "To infinity and beyond" indefinitely
# - With a sleep 2 in between each iteration
# - I am invicible!!! when receiving a SIGTERM signal

trap 'I am invincible!!!' SIGTERM
while true
do
    echo $"To infinity and beyond"
    sleep 2
done
