#!/usr/bin/env bash
#Executing ten times "Holberton School" with while loop using the conditional if for show "Hi"
i=1
while [ $i -le 10 ]
do
    echo $"Holberton School"
if [ $i -eq 9 ]
then
    echo $"Hi"
fi
    i=$(( i + 1 ))
done
