#!/usr/bin/env bash
#Executing ten times "Holberton School" with while loop using the conditional if for show "Hi"
i=1
while [ $i -le 10 ]
do
if [ $i -eq 4 ]
then
    echo $"bad luck"
elif [ $i -eq 8 ]
then
    echo $"good luck"
else
    echo $"Holberton School"
fi
    i=$(( i+1 ))
done
