#!/usr/bin/env bash
# Writing a Bash script that configures an Ubuntu server with the below requirements.

cp /etc/hosts ~/temporal
sed -i 's/127.0.0.1/127.0.0.2/g' ~/temporal
echo "8.8.8.8   facebook.com" >> ~/temporal
cp -f ~/temporal /etc/hosts
