#!/usr/bin/env bash
# Bash script to configure the containe

pkill -9 apache2
sed -i 's/80/8080/g' etc/nginx/sites-available/default
chmod ugo-wr /etc/nginx/nginx.conf
sed -i 'ls/.*/user nginx;/' /etc/nginx/nginx.conf
sudo -u nginx nginx
